### ISSUE TITLE
Players can get a negative balance if they buy a property they cannot afford.

### ISSUE THREAD

**Issue by SvenBrimstone** [Alig96/drp_Properties#1]
I know there's a way to submit new snippets of code, but I've never used github for that purpose and I don't have time this morning to find out. I fixed this by adding this:

if !ply:canAfford(Properties.PropertyDoors[propID].price) then
    DarkRP.notify(ply, 0, 4, "You cannot afford this property!")
return end

After line 155 (in the buyproperty function), so it checks to see if the player can afford the home.

**Comment by Alig96** [comment]
Thanks for the heads up, its now fixed in the master!
